version: '3'
services:
  main_broker:
    image: eclipse-mosquitto
    networks:
      - net0
  weather:
    image: eclipse-mosquitto
    networks:
      - net
  waste:
    image: eclipse-mosquitto
    networks:
      - net1
  city:
    image: eclipse-mosquitto
    networks:
      - net2
  appbackend:
    image: docker.linksmart.eu/mps:latest
    hostname: appbackend
    depends_on:
      - weather
      - main_broker
      - sc
    environment:
      - connection_broker_mqtt_hostname=main_broker
      - linksmart_service_catalog_endpoint=http://sc:8082
    networks:
      - net
      - net0
    links:
      - weather
  sc:
    image: linksmart/sc:latest
    depends_on:
      - weather
      - city
      - waste
      - main_broker
    links:
      - weather
      - waste
      - city
      - main_broker
    volumes:
      - ./conf/:/conf/
    command:
      - -conf
      - /conf/sc-conf.json
    networks:
      - net
      - net0
      - net1
      - net2
  agent:
    image: linksmart/dpa:snapshot
    hostname: agent
    depends_on:
      - weather
      - waste
      - city
      - sc
      - appbackend
      - main_broker
    links:
      - weather
      - waste
      - city
      - appbackend
      - sc
    environment:
      - api_events_mqtt_broker_incoming=weather,waste
      - messaging_client_mqtt_autoblacklisting=false
      - linksmart_service_catalog_endpoint=http://sc:8082
      - cep_init_bootstrapping_files=/data/bootstrapping/bootstrapping.json
    volumes:
      - ./conf/bootstrapping.json:/data/bootstrapping/bootstrapping.json
    networks:
      - net
      - net0
      - net1
      - net2
networks:
    net:
    net0:
    net1:
    net2:
