version: '3'
services:
  main_broker:
    image: eclipse-mosquitto
    ports:
      - "1880:1883"
    networks:
      - net0
  weather:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      - net
  waste:
    image: eclipse-mosquitto
    ports:
      - "1882:1883"
    networks:
      - net1
  city:
    image: eclipse-mosquitto
    ports:
      - "1881:1883"
    networks:
      - net2
  appbackend:
    image: docker.linksmart.eu/mps:latest
    hostname: appbackend
    depends_on:
      - weather
      - main_broker
      - sc
    environment:
      - connection_broker_mqtt_hostname=weather
      - linksmart_service_catalog_endpoint=http://sc:8082
    networks:
      - net
      - net0
    links:
      - weather
  sc:
    image: docker.linksmart.eu/sc:latest
    depends_on:
      - weather
      - city
      - waste
      - main_broker
    links:
      - weather
      - waste
      - city
      - main_broker
    volumes:
      - .\stm\sc-conf.json:/conf/sc-conf.json
    command:
      - -conf
      - /conf/sc-conf.json
    networks:
      - net
      - net0
      - net1
      - net2
    ports:
      - "8082:8082"
  agent:
    image: docker.linksmart.eu/agent:dpa-snapshot
    hostname: agent
    depends_on:
      - weather
      - waste
      - city
      - sc
      - appbackend
      - main_broker
    links:
      - weather
      - waste
      - city
      - appbackend
      - sc
    environment:
      - api_events_mqtt_broker_incoming=weather,waste
      - linksmart_service_catalog_endpoint=http://sc:8082
      - cep_init_bootstrapping_files=/data/bootstrapping/bootstrapping.json
    ports:
      - "8319:8319"
      - "5005:5005"
    volumes:
      - .\stm\bootstrapping.json:/data/bootstrapping/bootstrapping.json
    networks:
      - net
      - net0
      - net1
      - net2
    entrypoint:
      - "java"
      - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
      - "-cp"
      - "./*:/dependencies/*"
      - "org.springframework.boot.loader.PropertiesLauncher"
networks:
    net:
    net0:
    net1:
    net2:
