version: '3'
  agent:
    ports:
      - "8319:8319"
      - "5005:5005"
    entrypoint:
      - "java"
      - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
      - "-cp"
      - "./*:/dependencies/*"
      - "org.springframework.boot.loader.PropertiesLauncher"
