version: '3'
services:
  agent:
    image: docker.linksmart.eu/agent:dpa-experimental
    ports:
      - "8319:8319"
      - "5005:5005"
    entrypoint:
      - "java"
      - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      - "-cp"
      - "./*:/dependencies/*"
      - "org.springframework.boot.loader.PropertiesLauncher"
